# Generated by Django 5.1.2 on 2025-03-31 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_branch_userprofile_certifications_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='internships',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='leadership_score',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='live_backlogs',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='placement_prediction',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='placement_probability',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='prediction_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='programming_language',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='soft_skills_score',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='technical_skills',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='year_of_passing',
        ),
        migrations.CreateModel(
            name='PlacementPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=20)),
                ('probability', models.FloatField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('cgpa', models.FloatField(blank=True, null=True)),
                ('soft_skills_score', models.FloatField(blank=True, null=True)),
                ('technical_skills', models.FloatField(blank=True, null=True)),
                ('leadership_score', models.FloatField(blank=True, null=True)),
                ('experience_years', models.FloatField(blank=True, null=True)),
                ('live_backlogs', models.IntegerField(blank=True, null=True)),
                ('internships', models.IntegerField(blank=True, null=True)),
                ('projects', models.IntegerField(blank=True, null=True)),
                ('certifications', models.IntegerField(blank=True, null=True)),
                ('programming_language', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('year_of_passing', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_predictions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
